server:
  forward-headers-strategy: framework

spring:
  application:
    name: spring-security-api
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    jwt:
      secret: "minhachavesecreta"

spring-doc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  schemes:
    - http
    - https